name: real_to_endovis17
model_type: ImageCleanModel
scale: 1
num_gpu: 1

datasets:
  val:
    name: EndoVis17
    dataroot_lq: datasets/EndoVis17/low
    dataroot_gt: datasets/EndoVis17/high

network_g:
  type: RetinexFormer
  in_channels: 3
  out_channels: 3
  n_feat: 40
  stage: 1
  num_blocks: [1, 2, 2]

path:
  pretrain_network_g: weights/real_to_endovis17.pth
  strict_load_g: true
